services:
  - type: web
    name: eitacraque-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build:shared && npm run build:api:prod
    startCommand: npm --workspace @eitacraque/api run prisma:migrate && npm --workspace @eitacraque/api run prisma:seed && npm --workspace @eitacraque/api run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: MUX_TOKEN_ID
        sync: false
      - key: MUX_TOKEN_SECRET
        sync: false

  - type: web
    name: eitacraque-web
    runtime: node
    plan: free
    buildCommand: npm ci && VITE_API_URL=https://eitacraque-api.onrender.com npm run build:web
    startCommand: npm --workspace @eitacraque/web run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://eitacraque-api.onrender.com
